# Generated by Django 4.2.4 on 2023-09-03 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZazaUsers',
            new_name='Users',
        ),
    ]
